<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <IsPackable>false</IsPackable>
    <LangVersion>latest</LangVersion>
    <UserSecretsId>7cd5132a-1f06-4001-b62c-51cdcbe38dbf</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="CodeTemplates\**\*.hbs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.5" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="10.0.5" />
    <PackageReference Include="Microsoft.Extensions.Configuration.EnvironmentVariables" Version="10.0.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="10.0.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration.UserSecrets" Version="10.0.0" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.3.0" />
    <PackageReference Include="xunit" Version="2.9.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="3.1.5">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\EntityFrameworkCore.Scaffolding.Handlebars\EntityFrameworkCore.Scaffolding.Handlebars.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Update="CodeTemplates\CSharpDbContext\DbContext.hbs">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </None>
    <None Update="CodeTemplates\CSharpDbContext\Partials\DbImports.hbs">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </None>
    <None Update="CodeTemplates\CSharpDbContext\Partials\DbSets.hbs">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </None>
    <None Update="CodeTemplates\CSharpDbContext\Partials\DbOnConfiguring.hbs">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </None>
    <None Update="CodeTemplates\CSharpEntityType\Class.hbs">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </None>
    <None Update="CodeTemplates\CSharpEntityType\Partials\Constructor.hbs">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </None>
    <None Update="CodeTemplates\CSharpEntityType\Partials\Imports.hbs">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </None>
    <None Update="CodeTemplates\CSharpEntityType\Partials\Properties.hbs">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </None>
    <None Update="appsettings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
